#!/bin/bash

# Docker 컨테이너 이름
CONTAINER_NAME="enshrouded-server"

# 이미지 이름 (필요한 경우 이미지 태그도 포함)
IMAGE_NAME="sknnr/enshrouded-dedicated-server:latest"

# 도커 바인드 마운트 볼륨 디렉토리
DOCKER_DIRECTORY = 'your_directory'

# 서버명
YOUR_SERVER_NAME = 'your_server_name'

# 서버 비밀번호
YOUR_PASSWORD = 'your_password'

# 컨테이너가 이미 실행 중인지 확인
if [ $(docker ps --format '{{.Names}}' | grep -w ${CONTAINER_NAME}) ]; then
    echo "Container ${CONTAINER_NAME} is already running."
# 컨테이너가 중지 상태인지 확인
elif [ $(docker ps -a --format '{{.Names}}' | grep -w ${CONTAINER_NAME}) ]; then
    echo "Starting existing container ${CONTAINER_NAME}..."
    docker start ${CONTAINER_NAME}

    # 실행 확인
    ATTEMPTS=4
    SLEEP_TIME=3
    for (( i=1; i<=ATTEMPTS; i++ )); do
        echo "Checking if container ${CONTAINER_NAME} started... Attempt $i"
        if [ $(docker ps --format '{{.Names}}' | grep -w ${CONTAINER_NAME}) ]; then
            echo "Container ${CONTAINER_NAME} started successfully."
            exit 0
        fi
        sleep ${SLEEP_TIME}
    done
    echo "Failed to start container ${CONTAINER_NAME} after ${ATTEMPTS} attempts."
    exit 1
else
    # 컨테이너가 존재하지 않으면 새로 생성
    echo "Creating and starting new container ${CONTAINER_NAME}..."
sudo docker run \
  --detach \
  --name ${CONTAINER_NAME} \
  --mount type=bind,source=${DOCKER_DIRECTORY}, target=/home/steam/enshrouded/savegame \
  --publish 15636:15636/udp \
  --publish 15637:15637/udp \
  --env SERVER_NAME=${YOUR_SERVER_NAME} \
  --env SERVER_SLOTS=16 \
  --env SERVER_PASSWORD=${YOUR_PASSWORD} \
  --env GAME_PORT=15636 \
  --env QUERY_PORT=15637 \
  ${IMAGE_NAME}

    # 생성 확인
    ATTEMPTS=4
    SLEEP_TIME=3
    for (( i=1; i<=ATTEMPTS; i++ )); do
        echo "Checking if container ${CONTAINER_NAME} created and started... Attempt $i"
        if [ $(docker ps --format '{{.Names}}' | grep -w ${CONTAINER_NAME}) ]; then
            echo "Container ${CONTAINER_NAME} created and started successfully."
            exit 0
        fi
        sleep ${SLEEP_TIME}
    done
    echo "Failed to create and start container ${CONTAINER_NAME} after ${ATTEMPTS} attempts."
    exit 1
fi



  #!/bin/bash

# Docker 컨테이너 이름
CONTAINER_NAME="enshrouded-server"

docker stop ${CONTAINER_NAME}

# 컨테이너가 실행 중인지 확인
if [ $(docker ps --format '{{.Names}}' | grep -w ${CONTAINER_NAME}) ]; then
    # 종료 확인
    ATTEMPTS=5
    SLEEP_TIME=3
    for (( i=1; i<=ATTEMPTS; i++ )); do
        echo "Checking if container ${CONTAINER_NAME} is still running... Attempt $i"
        if [ $(docker ps --format '{{.Names}}' | grep -w ${CONTAINER_NAME}) ]; then
            echo "Container ${CONTAINER_NAME} is still running..."
            exit 0
        fi
        sleep ${SLEEP_TIME}
    done
      echo "Failed to stop container ${CONTAINER_NAME}."
# OS 리부트
else
  echo 'Rebooting the system...'
  sudo reboot
fi
